팔로우 페이지 추가기능
prgrms-fe-devcourse/FEDC3_Bigtoria_Off pull request #117
Opened 2023-01-16 14:03 UTC by kmww

#111 

## 작업 목록

- 온라인/오프라인
프로필에 온라인과 오프라인을 표시하도록함

- 프로필 사진 클릭
누르면 해당 유저의 스토리북으로 이동

- 추가사항
<s>언팔 -> 팔로우 -> 언팔 시 팔로우 아이디가 갱신되지 않아서 버그가 발생했음</s>(해결)

### 참고 사진이 있다면 첨부

<img src="https://user-images.githubusercontent.com/105067764/212695914-69729e2b-e794-496b-bd34-8d69b13e55d6.png" width="50%"/>

2023-01-16 14:29 UTC, metacode22 reviewed
코드 보니까 팔로우 기능 때매 꽤나 고생하셨을 것 같습니다... 고생하셨어요!!

2023-01-16 14:29 UTC, metacode22 commented on src/components/Follow/FollowingList.tsx
> +  isOnline: boolean | undefined;
size처럼 ?를 붙여주면 `| undefined` 생략할 수 있었던 것 같은데 혹시 아시나요..? 갑자기 기억이 안나네요. ㅋㅋㅋ

2023-01-16 14:29 UTC, metacode22 commented on src/hooks/useGetFollow.ts
> +          target.innerText = '팔로우';
react에서 state를 통해 화면을 재구성하는 것이 아니라 innerText, appendChild와 같은 메서드를 이용해 DOM에 직접 접근하여 변경하는 것이 데이터 추적 면에서 안티 패턴으로 얼핏 들었는데 관련 자료를 찾기가 어렵네요..! 제가 아까 했던 말들은 일단 흘려들어도 될 것 같습니다!

2023-01-16 14:29 UTC, metacode22 commented on src/apis/follow.ts
> +    return await http.post({
👍👍👍

2023-01-16 14:29 UTC, metacode22 approved these changes

2023-01-16 15:45 UTC, kmww commented on src/components/Follow/FollowingList.tsx
> +  isOnline: boolean | undefined;
맞아요 지금 고치고있습니다!

2023-01-16 15:45 UTC, kmww commented on src/hooks/useGetFollow.ts
> +          target.innerText = '팔로우';
안그래도 그거때문에 자료 찾고있는데
찾으면 공유하겠습니다

2023-01-16 16:02 UTC, tooooo1 requested changes
너무너무 고생하셨습니다앙 몇 가지 남기고 가요!

2023-01-16 16:02 UTC, tooooo1 commented on src/components/Follow/FollowingList.tsx
> +          )}
이거 줄일 수 있을 거 같은데 한번 같이 고민해 볼까요?

예를들어서 이렇게 할거같아요 저는

```suggestion
          <StateBadge
            isOnline={isOnline}>
            <Avatar
              src={src}
              sx={{ width: size, height: size }}
              onClick={() => navigate(ROUTES.STORY_BOOK_BY_USER_ID(userId))}
            />
          </StateBadge>
```

2023-01-16 16:02 UTC, tooooo1 commented on src/hooks/useGetFollow.ts
>    const handleClick = async (e: MouseEvent<HTMLButtonElement>) => {
혹시 이 함수 한번 더 리팩토링 고려해 보시는건 어떨까요?

2023-01-16 16:02 UTC, tooooo1 commented on src/pages/Following.tsx
> +            <FollowingButton
굿

2023-01-16 16:58 UTC, kmww commented on src/components/Follow/FollowingList.tsx
> +          )}
수정 했습니다~

2023-01-17 08:26 UTC, tooooo1 approved these changes

2023-01-17 08:26 UTC, merged