Feature/add title to story book
prgrms-fe-devcourse/FEDC3_Bigtoria_Off pull request #118
Opened 2023-01-16 14:34 UTC by metacode22

#22, #91

## 작업 목록
- 스토리북 진입 시 유저의 fullName 출력
- 햄버거에서 token이 존재할 때만 팔로우 목록 버튼이 나오도록 구현
- 스토리북 페이지에 팔로우 버튼 구현

### 참고 사진이 있다면 첨부
- mui 사용하면서 알게 되었는데, 밑과 같이 prop을 전달해서 mui 컴포넌트 스타일을 동적으로 변화시키고 싶다면 다음과 같이 이용하시면 될 것 같습니다. 나중에 디자인 바꿀 때 사용할 수 있지 않을까 싶어서 적어놔요!
```typescript
  return (
    <span>
      {!isMyStoryBook && canBeRendered && (
        <CustomButton
          variant='outlined'
          onClick={handleClick}
          isFollowing={isFollowing}>
          {isFollowing ? '팔로잉' : '팔로우'}
        </CustomButton>
      )}
    </span>
  );
};

export default FollowButton;

interface StyledButtonProps extends ButtonProps {
  isFollowing?: boolean;
}

const CustomButton = styled(Button, {
  shouldForwardProp: (prop) => prop !== 'isFollowing',
})<StyledButtonProps>(({ isFollowing }) => ({
  ...(isFollowing && {
    color: 'rgba(0, 0, 0, 0.26)',
    border: '1px solid rgba(0, 0, 0, 0.12)',
  }),
}));
```

2023-01-16 14:35 UTC, metacode22 commented on src/components/StoryBook/Loading.tsx
> +  height: 70vh;
이렇게 안하면 로딩이 너무 밑으로 내려가네요. 다른 방법이 있으면 말씀해주세요!

2023-01-16 14:36 UTC, metacode22 commented on src/components/shared/Header.tsx
> +        )}
조만간 팔로워 목록 버튼도 만들어야겠네요.

2023-01-16 14:41 UTC, metacode22 commented on src/components/StoryBook/FollowButton.tsx
> +      {!isMyStoryBook && canBeRendered && (
깜빡임 없애려고 처음엔 useLayoutEffect도 사용해봤는데 해당 훅 안에서 비동기 통신을 하면 결국 useEffect와 별반 다를게 없었어요. 그래서 canBeRendered라는 state를 한 개 더 만들어서 isFollowing이 set되고 나서, 그니까 아예 준비가 되면 렌더링 되게 했습니다. 더 좋은 방법 있으면 말씀해주세요!

2023-01-16 16:03 UTC, kmww reviewed
수고 많으셨어요!!

2023-01-16 16:03 UTC, kmww commented on src/components/StoryBook/FollowButton.tsx
> +        newFollowId && setIsFollowing(true);
```suggestion
 if (newFollowId) {
   setFollowId(newFollowId);
   setIsFollowing(true);
 }
```
코드 줄이 길어지지만 이런식으로 사용할 수도있을것 같아요

2023-01-16 16:03 UTC, kmww commented on src/components/StoryBook/FollowButton.tsx
> +        const following = followings.find((f) => f.user === userId);
여기 f는 팔로잉 데이터 객체인가요?

2023-01-16 16:03 UTC, kmww commented on src/components/StoryBook/FollowButton.tsx
> +      setCanBeRendered(true);
isReady 로 간단하게 나타낸는 것도 좋을것 같아요

2023-01-16 16:03 UTC, kmww commented on src/components/StoryBook/StoryBookTitle.tsx
> +    </Container>
👍👍👍👍👍

2023-01-16 16:03 UTC, kmww commented on src/pages/StoryBook.tsx
> +        {!!fullName && <StoryBookTitle fullName={fullName} />}
요기 느낌표 두번은 어떤 작동을 하나요?😅

2023-01-16 16:08 UTC, tooooo1 requested changes
와 엄청 알찬 PR이네요 ㅎㅎ

2023-01-16 16:08 UTC, tooooo1 commented on src/components/StoryBook/FollowButton.tsx
> +  const handleClick = async () => {
이 함수 한번 리팩토링 고려해보시는건 어떨까요?

2023-01-16 16:08 UTC, tooooo1 commented on src/components/StoryBook/FollowButton.tsx
> +      {!isMyStoryBook && canBeRendered && (
정확한건 확인을 안 해봐서 모르겠지만 데이터가 없을 때 보여지는 컴포넌트가 없어서 깜빡임이 있는거 같아요. and연산자라서.

2023-01-16 16:08 UTC, tooooo1 commented on src/components/StoryBook/Loading.tsx
> +  height: 70vh;
정확히 가운데에 로딩을 띄우고 싶으시다면 absolute와 positionXY 50%, 50%가 있을거같아요

2023-01-16 16:08 UTC, tooooo1 commented on src/components/shared/Header.tsx
> +        )}
멋져요

2023-01-16 16:08 UTC, tooooo1 commented on src/hooks/useFetchStories.ts
>  const TOTAL_MONTHS_NUMBER = 12;
오 넘 좋아요

2023-01-17 05:56 UTC, metacode22 commented on src/components/StoryBook/FollowButton.tsx
> +        const following = followings.find((f) => f.user === userId);
넵!

2023-01-17 06:00 UTC, metacode22 commented on src/pages/StoryBook.tsx
> +        {!!fullName && <StoryBookTitle fullName={fullName} />}
fullName이 빈 문자열이면 false로, 빈 문자열이 아니면 true가 돼요! 확실하게 boolean으로 하려고 그냥 썼어요!

2023-01-17 06:18 UTC, metacode22 commented on src/components/StoryBook/FollowButton.tsx
> +  const handleClick = async () => {
리팩터링 했는데 한 번 봐주시겠어요?😀

2023-01-17 08:27 UTC, tooooo1 approved these changes

2023-01-17 08:27 UTC, merged