팔로우 페이지 다크모드
prgrms-fe-devcourse/FEDC3_Bigtoria_Off pull request #234
Opened 2023-01-27 12:11 UTC by kmww

## 작업 목록
- 팔로잉, 팔로우 버튼 마진 통일
- 다크모드 수정
- FOLLOWING / FOLLOWER 탭에 따라서 해당 페이지 렌더링

### 참고 사진이 있다면 첨부
전
<img src="https://user-images.githubusercontent.com/105067764/215083653-6f2fda3e-884a-4459-9f0c-a92c5ae5053a.png" width='40%' />
후
<img src="https://user-images.githubusercontent.com/105067764/215083661-d282feed-c020-4b0c-bf27-095fb6e0af9b.png" width='40%' />

## 예정
팔로잉과 팔로워의 변경이 있을때만 api를 호출하도록 최적화

2023-01-27 12:33 UTC, metacode22 approved these changes
LGTM!!!

2023-01-27 15:35 UTC, glassk approved these changes
좋습니다 👍

2023-01-27 15:35 UTC, glassk commented on src/pages/follow.tsx
> +  }, [value]);
저도 이 훅이 필요한 곳이 있는지 다시 확인해보겠습니다
눈에 띄는 차이가 있었는지 궁금합니다!

2023-01-27 21:36 UTC, tooooo1 requested changes
팔로우 페이지 다크모드가 더 향상되었네요 ㅋㅋ 다크모드 호환성은 앞으로의 숙제군요

2023-01-27 21:36 UTC, tooooo1 commented on src/pages/follow.tsx
> +    props.display === 'dark' ? '#121212' : 'white'};
`#121212`컬러가 새로 나왔는데요. 아마 직접 만드신 거 같아요.

통일성을 위해 기존 constant에 있는 COLOR에서 정의한 색을 사용하는 건 어떨까요?

2023-01-27 21:36 UTC, tooooo1 commented on src/pages/follow.tsx
> +  }, [value]);
기존 useEffect에서 useLayoutEffect로 변경하셨네요! 혹시 변경 전과 후에 대해서 어떤 차이가 있었는지 궁금해용

2023-01-28 05:18 UTC, kmww commented on src/pages/follow.tsx
> +  }, [value]);
너무 깜빡거림이 심해서 알아봤는데,
useEffect의 경우 컴포넌트가 `render`와 `paint` 이후에 `비동기` 적으로 실행되고
useLayoutEffect의 경우 컴포넌트가 `render`된 후 `동기적`으로 실행되고 `paint`가 됩니다.
useEffect내부에서 데이터를 가져온 뒤 그려주는것을 원했고 유저의 info만 받아서 뿌려주는 복잡하지 않은 로직이라고 생각해서 사용했습니다. 실제로 깜빡임이 줄어든것을 확인할 수 있었습니다.

2023-01-28 05:31 UTC, kmww commented on src/pages/follow.tsx
> +    props.display === 'dark' ? '#121212' : 'white'};
원래있던 왼쪽부분의 색이 다크모드의 메인 색이라고 생각했고,
왼쪽과 색을 맞추기 위해서 사용했는데 `#121212` 다른페이지는 `#1e1e1e` 를 사용하고 있었네요..😅

2023-01-28 05:55 UTC, tooooo1 approved these changes

2023-01-28 07:24 UTC, merged